#!/bin/bash

ROOT_UID=0

# check command avalibility
function has_command() {
    command -v $1 > /dev/null
}

if [ "$UID" -eq "$ROOT_UID" ]; then

  # Copy Vimix
  cp -a Vimix /boot/grub/themes

  # Set Vimix
  grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME=/d' /etc/default/grub
  echo "GRUB_THEME=\"/boot/grub/themes/Vimix/theme.txt\"" >> /etc/default/grub

  # update grub
  if has_command update-grub; then
  update-grub
  
  elif has_command grub-mkconfig; then
  grub-mkconfig -o /boot/grub/grub.cfg

  elif has_command grub2-mkconfig; then
  grub2-mkconfig -o /boot/grub/grub.cfg

  fi
  echo -e "/n All done!"
  notify-send "All done!" -i face-smile

else
  echo -e "/n Please run this script by root..."
  notify-send "Please run this script by root..." -i notification
fi


